### ISSUE TITLE
tensorflow requirement should be tensorflow-gpu

### ISSUE THREAD

**Issue by Zohaggie** [sermakarevich/jigsaw-toxic-comment-classification-challenge#3]
The requirements file lists tensorflow==1.6.0. However pip install only installed the CPU version, I had to install tensorflow-gpu to get the models to work. Consider amending the requirements file - would tensorflow-gpu==1.6.0 work?

**Comment by sermakarevich** [comment]
It is better to install it as instructed on tensorflow site as you need to have proper version of CUDA and Cudnn installed as well.

**Comment by Zohaggie** [comment]
I agree. I was just pointing out that relying on the requirements file to create an environment has a flaw, perhaps it can be tweaked, perhaps you can make a note of specific requirements in your readme?

Can you please at least let us know the specifications of the hardware you trained on? I have a very limited GPU and it chokes on the predict tasks, even after halving the batch size, so I'd like a clearer picture of whats needed so I can set up an appropriate machine on AWS.

**Comment by sermakarevich** [comment]
I have 1080Ti
